export const PROJECT_TYPES = {
    NODE: 'Node.js',
    PYTHON: 'Python',
    JAVA: 'Java',
    DOTNET: '.NET',
    RUBY: 'Ruby',
    GO: 'Go',
    RUST: 'Rust',
    REACT: 'React',
    ANGULAR: 'Angular',
    VUE: 'Vue',
    SVELTE: 'Svelte',
    NEXTJS: 'Next.js',
    NUXTJS: 'Nuxt.js',
    LARAVEL: 'Laravel',
    SYMFONY: 'Symfony',
    DJANGO: 'Django',
    FLASK: 'Flask',
    EXPRESS: 'Express',
    SPRING: 'Spring',
    HIBERNATE: 'Hibernate',
    FLUTTER: 'Flutter',
    UNKNOWN: 'Unknown'
};

export const GENERAL_DEV_TOOLS = [
    'rainbow brackets',
    'gitlens',
    'docker',
    'prettier',
    'eslint',
    'debugger for chrome',
    'live share',
    'remote - ssh',
    'code runner',
    'live server',
    'auto rename tag',
    'bracket pair colorizer',
    'indent-rainbow',
    'todo tree',
    'path intellisense',
    'vscode-icons',
    'material icon theme',
    'markdown all in one',
    'code spell checker',
    'git history',
    'gitignore',
    'better comments',
    'peacock',
    'rest client',
    'settings sync'
];

